const CLINIC_PLACEHOLDER_IMAGE = "/clinic/home/instagram/team/team-placeholder.webp";

export const clinicImages = {
  placeholder: CLINIC_PLACEHOLDER_IMAGE,
  gallery: {
    categories: {
      environment: "/clinic/gallery/categories/clinic-environment.jpg",
      beforeAfter: "/clinic/gallery/categories/before-after.jpg",
      equipment: "/clinic/gallery/categories/equipment.png",
      team: "/clinic/gallery/categories/team.png",
    },
    equipment: [
      "/clinic/gallery/equipment/equipment-01.webp",
      "/clinic/gallery/equipment/equipment-02.webp",
      "/clinic/gallery/equipment/equipment-03.webp",
      "/clinic/gallery/equipment/equipment-04.webp",
      "/clinic/gallery/equipment/equipment-05.webp",
      "/clinic/gallery/equipment/equipment-06.webp",
      "/clinic/gallery/equipment/equipment-07.webp",
      "/clinic/gallery/equipment/equipment-08.webp",
      "/clinic/gallery/equipment/equipment-09.webp",
      "/clinic/gallery/equipment/equipment-10.webp",
      "/clinic/gallery/equipment/equipment-11.webp",
      "/clinic/gallery/equipment/equipment-12.webp",
      "/clinic/gallery/equipment/equipment-13.webp",
      CLINIC_PLACEHOLDER_IMAGE,
    ],
    environment: [
      "/clinic/gallery/environment/environment-01.webp",
      "/clinic/gallery/environment/environment-02.webp",
      "/clinic/gallery/environment/environment-03.webp",
      "/clinic/gallery/environment/environment-04.webp",
      "/clinic/gallery/environment/environment-05.webp",
      "/clinic/gallery/environment/environment-06.webp",
      "/clinic/gallery/environment/environment-07.webp",
      "/clinic/gallery/environment/environment-08.webp",
      "/clinic/gallery/environment/environment-09.webp",
      "/clinic/gallery/environment/environment-10.webp",
      "/clinic/gallery/environment/environment-11.webp",
      "/clinic/gallery/environment/environment-12.webp",
      "/clinic/gallery/environment/environment-13.webp",
      "/clinic/gallery/environment/environment-14.webp",
      "/clinic/gallery/environment/environment-15.webp",
      "/clinic/gallery/environment/environment-16.webp",
      "/clinic/gallery/environment/environment-17.webp",
      "/clinic/gallery/environment/environment-18.webp",
      "/clinic/gallery/environment/environment-19.webp",
      "/clinic/gallery/environment/environment-20.webp",
      "/clinic/gallery/environment/environment-21.webp",
      "/clinic/gallery/environment/environment-22.webp",
      "/clinic/gallery/environment/environment-23.webp",
      "/clinic/gallery/environment/environment-24.webp",
      "/clinic/gallery/environment/environment-25.webp",
      "/clinic/gallery/environment/environment-26.webp",
      "/clinic/gallery/environment/environment-27.webp",
      "/clinic/gallery/environment/environment-28.webp",
      "/clinic/gallery/environment/environment-29.webp",
      "/clinic/gallery/environment/environment-30.webp",
      "/clinic/gallery/environment/environment-31.webp",
      "/clinic/gallery/environment/environment-32.webp",
      "/clinic/gallery/environment/environment-33.webp",
      "/clinic/gallery/environment/environment-34.webp",
      "/clinic/gallery/environment/environment-35.webp",
      "/clinic/gallery/environment/environment-36.webp",
      "/clinic/gallery/environment/environment-37.webp",
    ],
    team: ["/clinic/gallery/team/team-01.webp"],
  },
  home: {
    finalCta: "/clinic/home/final-cta/final-cta-102.webp",
    results: "/clinic/home/results/results-132.webp",
    doctor: [
      "/clinic/home/doctor/doctor-133.webp",
      "/clinic/home/doctor/doctor-134.webp",
      "/clinic/home/doctor/doctor-135.webp",
      "/clinic/home/doctor/doctor-136.webp",
      "/clinic/home/doctor/doctor-137.webp",
      "/clinic/home/doctor/doctor-138.webp",
    ],
    instagram: {
      event: [
        "/clinic/home/instagram/event/event-117.webp",
        "/clinic/home/instagram/event/event-118.webp",
        "/clinic/home/instagram/event/event-119.webp",
        "/clinic/home/instagram/event/event-120.webp",
        "/clinic/home/instagram/event/event-121.webp",
        "/clinic/home/instagram/event/event-placeholder-221.webp",
      ],
      team: [CLINIC_PLACEHOLDER_IMAGE],
      clients: [
        "/clinic/home/instagram/clients/clients-14.webp",
        "/clinic/home/instagram/clients/clients-15.webp",
        "/clinic/home/instagram/clients/clients-16.webp",
        "/clinic/home/instagram/clients/clients-17.webp",
        "/clinic/home/instagram/clients/clients-18.webp",
        "/clinic/home/instagram/clients/clients-19.webp",
        "/clinic/home/instagram/clients/clients-110.webp",
        "/clinic/home/instagram/clients/clients-111.webp",
        "/clinic/home/instagram/clients/clients-112.webp",
        "/clinic/home/instagram/clients/clients-113.webp",
        "/clinic/home/instagram/clients/clients-114.webp",
        "/clinic/home/instagram/clients/clients-115.webp",
        "/clinic/home/instagram/clients/clients-116.webp",
      ],
      amwc: [
        "/clinic/home/instagram/amwc/amwc-123.webp",
        "/clinic/home/instagram/amwc/amwc-124.webp",
        "/clinic/home/instagram/amwc/amwc-125.webp",
        "/clinic/home/instagram/amwc/amwc-126.webp",
        "/clinic/home/instagram/amwc/amwc-127.webp",
        "/clinic/home/instagram/amwc/amwc-128.webp",
        "/clinic/home/instagram/amwc/amwc-129.webp",
        "/clinic/home/instagram/amwc/amwc-130.webp",
        "/clinic/home/instagram/amwc/amwc-131.webp",
      ],
    },
  },
} as const;
